GET http://localhost:8080/appointments

###

GET http://localhost:8080/appointments/67b2e9c556e2149a3f392bcd

###

POST http://localhost:8080/appointments
Content-Type: application/json

{
    "title": "testing",
    "start": "2025-02-09T15:00:00.000+00:00",
    "end": "2025-02-14T03:00:00.000+00:00"
}

###

DELETE http://localhost:8080/appointments/67b2e9c556e2149a3f392bcd

###

PATCH http://localhost:8080/appointments/67b40d9e3f9790ba40453f8e
Content-Type: application/json

{
    "title": "new title"
}

###

POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "email": "hugh.cameron102@gmail.com",
    "password": "avatar34"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "hugh.cameron102@gmail.com",
    "password": "avatar34"
}

POST http://localhost:8080/auth/logout